/* graph2note — shared mutable state + element registry (U1 module split).
   Views import { state, el } instead of sharing one giant closure. */
"use strict";

import { $ } from "./utils.js";

export const state = {
  route: "library",
  docId: null,
  doc: null,        // last loaded document record
  busy: false,
  pollTimer: null,
  jobId: null,
  pdfId: null,
  searchActive: false,
  searchQuery: "",
  pdfQaSessionId: null,   // P1 multi-turn conversation id
  pdfQaScopeKey: null,    // scope the current conversation is bound to
  pdfQaHistory: [],       // conversation turns [{index, question, status, ...}]
  askSessions: [],        // persisted session summaries (history list)
  askBusy: false,         // a turn is in flight (composer disabled)
  libraryCollection: null,
  libraryFilter: "all",
  libraryTag: null,
  libraryTopic: null,
  libraryDensity: null,   // U2 grid density (comfortable/compact)
  timelineGroup: "day",
  digestId: null,      // A2: selected weekly digest id
  llmSettings: null,
};

export const el = {
  appShell: $("#app-shell"),
  sidebar: $("#app-sidebar"),
  sidebarToggle: $("#sidebar-toggle"),
  globalSearchForm: $("#global-search-form"),
  globalSearchInput: $("#global-search-input"),
  libraryZone: $("#library-zone"),
  libraryFilters: $("#library-filters"),
  libraryDensity: $("#library-density"),
  inboxZone: $("#inbox-zone"),
  inboxEmpty: $("#inbox-empty"),
  inboxList: $("#inbox-list"),
  tagsZone: $("#tags-zone"),
  settingsZone: $("#settings-zone"),
  llmProviderList: $("#llm-provider-list"),
  llmChannelList: $("#llm-channel-list"),
  llmHealthList: $("#llm-health-list"),
  llmHealthButton: $("#llm-health-button"),
  llmSaveButton: $("#llm-save-button"),
  llmCustomForm: $("#llm-custom-form"),
  llmCustomId: $("#llm-custom-id"),
  llmCustomName: $("#llm-custom-name"),
  llmCustomBase: $("#llm-custom-base"),
  llmCustomKey: $("#llm-custom-key"),
  llmCustomModels: $("#llm-custom-models"),
  llmCustomSubmit: $("#llm-custom-submit"),
  llmCustomCancel: $("#llm-custom-cancel"),
  llmCustomHint: $("#llm-custom-form-hint"),
  llmCustomList: $("#llm-custom-list"),
  timelineZone: $("#timeline-zone"),
  graphZone: $("#graph-zone"),
  graphEmpty: $("#graph-empty"),
  graphScroll: $("#graph-scroll"),
  graphCanvas: $("#graph-canvas"),
  // U4 graph interaction controls (zoom / pan / filter / cluster)
  graphZoomIn: $("#graph-zoom-in"),
  graphZoomOut: $("#graph-zoom-out"),
  graphZoomValue: $("#graph-zoom-value"),
  graphFit: $("#graph-fit"),
  graphReset: $("#graph-reset"),
  graphStatus: $("#graph-status"),
  graphFilterZone: $("#graph-filters"),
  graphSourceChips: $("#graph-source-chips"),
  graphSetChips: $("#graph-set-chips"),
  graphTagChips: $("#graph-tag-chips"),
  graphClearFilters: $("#graph-clear-filters"),
  graphClustersToggle: $("#graph-clusters-toggle"),
  dashboardZone: $("#dashboard-zone"),
  dashboardEmpty: $("#dashboard-empty"),
  dashboardContent: $("#dashboard-content"),
  dashboardQualityLabel: $("#dashboard-quality-label"),
  dashboardPeriods: $("#dashboard-periods"),
  dashboardQuality: $("#dashboard-quality"),
  dashboardTrend: $("#dashboard-trend"),
  dashboardCategories: $("#dashboard-categories"),
  dashboardTags: $("#dashboard-tags"),
  dashboardModels: $("#dashboard-models"),
  dashboardDay: $("#dashboard-day"),
  dashboardMonth: $("#dashboard-month"),
  // A2 每周小结（数据看板区块）
  digestPanel: $("#digest-panel"),
  digestRange: $("#digest-range"),
  digestFrom: $("#digest-from"),
  digestFromSep: $("#digest-from-sep"),
  digestTo: $("#digest-to"),
  digestForce: $("#digest-force"),
  digestGenerate: $("#digest-generate"),
  digestStatus: $("#digest-status"),
  digestHistory: $("#digest-history"),
  digestViewer: $("#digest-viewer"),
  digestViewerMeta: $("#digest-viewer-meta"),
  digestViewerContent: $("#digest-viewer-content"),
  digestEmpty: $("#digest-empty"),
  timelineGroups: $("#timeline-groups"),
  timelineEmpty: $("#timeline-empty"),
  timelineUndated: $("#timeline-undated"),
  timelineUndatedCount: $("#timeline-undated-count"),
  timelineUndatedItems: $("#timeline-undated-items"),
  timelineGroup: $("#timeline-group"),
  timelineDensity: $("#timeline-density"),
  libraryGrid: $("#library-grid"),
  libraryEmpty: $("#library-empty"),
  libraryCount: $("#library-count"),
  libraryFilterLabel: $("#library-filter-label"),
  collectionSuggestions: $("#collection-suggestions"),
  collectionTree: $("#collection-tree"),
  collectionCreateForm: $("#collection-create-form"),
  collectionCreateInput: $("#collection-create-input"),
  documentCollectionForm: $("#document-collection-form"),
  documentCollectionSelect: $("#document-collection-select"),
  documentCollectionList: $("#document-collection-list"),
  tagList: $("#tag-list"),
  tagCreateForm: $("#tag-create-form"),
  tagCreateInput: $("#tag-create-input"),
  uploadZone: $("#upload-zone"),
  uploadCard: $("#upload-card"),
  fileInput: $("#file-input"),
  pickFile: $("#pick-file"),
  uploadHint: $("#upload-hint"),
  workingZone: $("#working-zone"),
  workingText: $("#working-text"),
  workingDetail: $("#working-detail"),
  workZone: $("#work-zone"),
  docToolbar: $("#doc-toolbar"),
  docMain: $("#doc-main"),
  docSidePanel: $("#doc-side-panel"),
  docPanelToggle: $("#doc-panel-toggle"),
  docPanelClose: $("#doc-panel-close"),
  originalImg: $("#original-img"),
  btnZoomImage: $("#btn-zoom-image"),
  imageViewer: $("#image-viewer"),
  imageViewerStage: $("#image-viewer-stage"),
  imageViewerImg: $("#image-viewer-img"),
  viewerZoomIn: $("#viewer-zoom-in"),
  viewerZoomOut: $("#viewer-zoom-out"),
  viewerFit: $("#viewer-fit"),
  viewerZoomLabel: $("#viewer-zoom-label"),
  viewerClose: $("#viewer-close"),
  mdEditor: $("#md-editor"),
  preview: $("#preview"),
  statusText: $("#status-text"),
  warnings: $("#warnings"),
  versionInfo: $("#version-info"),
  versionList: $("#version-list"),
  versionCompare: $("#version-compare"),
  versionReadonlyNote: $("#version-readonly-note"),
  // S3 version comparison overlay (read-only; lives inside #doc-main).
  diffView: $("#diff-view"),
  diffSelectA: $("#diff-select-a"),
  diffSelectB: $("#diff-select-b"),
  diffSwap: $("#diff-swap"),
  diffCompare: $("#diff-compare"),
  diffClose: $("#diff-close"),
  diffSummary: $("#diff-summary"),
  diffEmpty: $("#diff-empty"),
  diffHeadA: $("#diff-head-a"),
  diffHeadB: $("#diff-head-b"),
  diffRows: $("#diff-rows"),
  diffReadonly: $("#diff-readonly"),
  diffBackLatest: $("#diff-back-latest"),
  documentTagForm: $("#document-tag-form"),
  documentTagInput: $("#document-tag-input"),
  documentTagList: $("#document-tag-list"),
  metadataDocumentTime: $("#metadata-document-time"),
  metadataNeedsOrganization: $("#metadata-needs-organization"),
  metadataCaptureTime: $("#metadata-capture-time"),
  metadataImportTime: $("#metadata-import-time"),
  metadataModifiedTime: $("#metadata-modified-time"),
  metadataEvidence: $("#metadata-evidence"),
  metadataSave: $("#metadata-save"),
  saveIndicator: $("#save-indicator"),
  toast: $("#toast"),
  btnReparse: $("#btn-reparse"),
  btnCopy: $("#btn-copy"),
  btnDownload: $("#btn-download"),
  btnDelete: $("#btn-delete"),
  btnRepic: $("#btn-repic"),
  navLibrary: $("#nav-library"),
  navInbox: $("#nav-inbox"),
  navTimeline: $("#nav-timeline"),
  navGraph: $("#nav-graph"),
  navDashboard: $("#nav-dashboard"),
  navSettings: $("#nav-settings"),
  navVaultExport: $("#nav-vault-export"),
  navTags: $("#nav-tags"),
  navAsk: $("#nav-ask"),
  navUpload: $("#nav-upload"),
  modelLabel: $("#model-label"),
  vaultExportZone: $("#vault-export-zone"),
  vaultExportForm: $("#vault-export-form"),
  vaultExportDir: $("#vault-export-dir"),
  btnVaultExport: $("#btn-vault-export"),
  vaultExportStatus: $("#vault-export-status"),
  pickPdf: $("#pick-pdf"),
  pdfInput: $("#pdf-input"),
  pdfZone: $("#pdf-zone"),
  pdfList: $("#pdf-list"),
  pdfFilename: $("#pdf-filename"),
  pdfSummary: $("#pdf-summary"),
  pdfRetry: $("#pdf-retry"),
  // Keyword-search toolbar (aux tool inside the ask view; P3 owns unified search).
  pdfSearchForm: $("#pdf-search-form"),
  pdfSearchInput: $("#pdf-search-input"),
  pdfSearchScope: $("#pdf-search-scope"),
  pdfSearchStatus: $("#pdf-search-status"),
  pdfSearchResults: $("#pdf-search-results"),
  pdfSearchClear: $("#pdf-search-clear"),
  pdfQaForm: $("#pdf-qa-form"),
  pdfQaInput: $("#pdf-qa-input"),
  pdfQaNew: $("#pdf-qa-new"),
  pdfQaStatus: $("#pdf-qa-status"),
  pdfQaHistory: $("#pdf-qa-history"),
  // First-class Q&A conversation view (P2).
  askZone: $("#ask-zone"),
  askScope: $("#pdf-qa-scope"),
  askEmpty: $("#ask-empty"),
  askSessions: $("#ask-sessions"),
  askSessionsCount: $("#ask-sessions-count"),
  // R1 黑图修复报告：zone 由 /static/repair.js（classic，先于模块执行）注入。
  repairZone: $("#repair-zone"),
  // P3 论文阅读视图（paper.js 注册；只读展示）。
  paperZone: $("#paper-zone"),
  paperBack: $("#paper-back"),
  paperStatus: $("#paper-status"),
  paperMeta: $("#paper-meta"),
  paperSectionNav: $("#paper-section-nav"),
  paperBody: $("#paper-body"),
  paperReferencesZone: $("#paper-references-zone"),
  paperReferences: $("#paper-references"),
};

/* Views routed by location.hash; every routable zone is hidden before the
   active one is shown (U1 keeps the single-zone-at-a-time contract). */
export const ZONES = [
  el.libraryZone, el.tagsZone, el.askZone, el.inboxZone, el.settingsZone,
  el.timelineZone, el.graphZone, el.dashboardZone, el.uploadZone,
  el.workingZone, el.workZone, el.vaultExportZone, el.pdfZone, el.repairZone,
  el.paperZone,
];

export function hideAll() {
  ZONES.forEach((node) => { if (node) node.classList.add("hidden"); });
}

export function setBusy(busy) {
  state.busy = busy;
  [el.btnReparse, el.btnCopy, el.btnDownload, el.btnDelete, el.navUpload]
    .forEach((node) => { if (node) node.disabled = busy; });
}
