/* graph2note — shared mutable state + element registry (U1 module split).
   Views import { state, el } instead of sharing one giant closure. */
"use strict";

import { $ } from "./utils.js";

export const state = {
  route: "library",
  docId: null,
  doc: null,        // last loaded document record
  busy: false,
  pollTimer: null,
  jobId: null,
  pdfId: null,
  searchActive: false,
  searchQuery: "",
  libraryCollection: null,
  libraryFilter: "all",
  libraryTag: null,
  libraryTopic: null,
  timelineGroup: "day",
  llmSettings: null,
};

export const el = {
  appShell: $("#app-shell"),
  sidebar: $("#app-sidebar"),
  sidebarToggle: $("#sidebar-toggle"),
  globalSearchForm: $("#global-search-form"),
  globalSearchInput: $("#global-search-input"),
  libraryZone: $("#library-zone"),
  libraryFilters: $("#library-filters"),
  inboxZone: $("#inbox-zone"),
  inboxEmpty: $("#inbox-empty"),
  inboxList: $("#inbox-list"),
  tagsZone: $("#tags-zone"),
  settingsZone: $("#settings-zone"),
  llmProviderList: $("#llm-provider-list"),
  llmChannelList: $("#llm-channel-list"),
  llmHealthList: $("#llm-health-list"),
  llmHealthButton: $("#llm-health-button"),
  llmSaveButton: $("#llm-save-button"),
  timelineZone: $("#timeline-zone"),
  graphZone: $("#graph-zone"),
  graphEmpty: $("#graph-empty"),
  graphScroll: $("#graph-scroll"),
  graphCanvas: $("#graph-canvas"),
  dashboardZone: $("#dashboard-zone"),
  dashboardEmpty: $("#dashboard-empty"),
  dashboardContent: $("#dashboard-content"),
  dashboardQualityLabel: $("#dashboard-quality-label"),
  dashboardPeriods: $("#dashboard-periods"),
  dashboardQuality: $("#dashboard-quality"),
  dashboardTrend: $("#dashboard-trend"),
  dashboardCategories: $("#dashboard-categories"),
  dashboardTags: $("#dashboard-tags"),
  dashboardModels: $("#dashboard-models"),
  dashboardDay: $("#dashboard-day"),
  dashboardMonth: $("#dashboard-month"),
  timelineGroups: $("#timeline-groups"),
  timelineEmpty: $("#timeline-empty"),
  timelineUndated: $("#timeline-undated"),
  timelineUndatedCount: $("#timeline-undated-count"),
  timelineUndatedItems: $("#timeline-undated-items"),
  timelineGroup: $("#timeline-group"),
  libraryGrid: $("#library-grid"),
  libraryEmpty: $("#library-empty"),
  libraryCount: $("#library-count"),
  libraryFilterLabel: $("#library-filter-label"),
  collectionTree: $("#collection-tree"),
  collectionCreateForm: $("#collection-create-form"),
  collectionCreateInput: $("#collection-create-input"),
  documentCollectionForm: $("#document-collection-form"),
  documentCollectionSelect: $("#document-collection-select"),
  documentCollectionList: $("#document-collection-list"),
  tagList: $("#tag-list"),
  tagCreateForm: $("#tag-create-form"),
  tagCreateInput: $("#tag-create-input"),
  uploadZone: $("#upload-zone"),
  uploadCard: $("#upload-card"),
  fileInput: $("#file-input"),
  pickFile: $("#pick-file"),
  uploadHint: $("#upload-hint"),
  workingZone: $("#working-zone"),
  workingText: $("#working-text"),
  workingDetail: $("#working-detail"),
  workZone: $("#work-zone"),
  originalImg: $("#original-img"),
  mdEditor: $("#md-editor"),
  preview: $("#preview"),
  statusText: $("#status-text"),
  warnings: $("#warnings"),
  versionInfo: $("#version-info"),
  documentTagForm: $("#document-tag-form"),
  documentTagInput: $("#document-tag-input"),
  documentTagList: $("#document-tag-list"),
  metadataDocumentTime: $("#metadata-document-time"),
  metadataNeedsOrganization: $("#metadata-needs-organization"),
  metadataCaptureTime: $("#metadata-capture-time"),
  metadataImportTime: $("#metadata-import-time"),
  metadataModifiedTime: $("#metadata-modified-time"),
  metadataEvidence: $("#metadata-evidence"),
  metadataSave: $("#metadata-save"),
  saveIndicator: $("#save-indicator"),
  toast: $("#toast"),
  btnReparse: $("#btn-reparse"),
  btnCopy: $("#btn-copy"),
  btnDownload: $("#btn-download"),
  btnDelete: $("#btn-delete"),
  btnRepic: $("#btn-repic"),
  navLibrary: $("#nav-library"),
  navInbox: $("#nav-inbox"),
  navTimeline: $("#nav-timeline"),
  navGraph: $("#nav-graph"),
  navDashboard: $("#nav-dashboard"),
  navSettings: $("#nav-settings"),
  navVaultExport: $("#nav-vault-export"),
  navTags: $("#nav-tags"),
  navPdfSearch: $("#nav-pdf-search"),
  navUpload: $("#nav-upload"),
  modelLabel: $("#model-label"),
  vaultExportZone: $("#vault-export-zone"),
  vaultExportForm: $("#vault-export-form"),
  vaultExportDir: $("#vault-export-dir"),
  btnVaultExport: $("#btn-vault-export"),
  vaultExportStatus: $("#vault-export-status"),
  pickPdf: $("#pick-pdf"),
  pdfInput: $("#pdf-input"),
  pdfZone: $("#pdf-zone"),
  pdfList: $("#pdf-list"),
  pdfFilename: $("#pdf-filename"),
  pdfSummary: $("#pdf-summary"),
  pdfRetry: $("#pdf-retry"),
  pdfSearchZone: $("#pdf-search-zone"),
  pdfSearchForm: $("#pdf-search-form"),
  pdfSearchInput: $("#pdf-search-input"),
  pdfSearchScope: $("#pdf-search-scope"),
  pdfSearchStatus: $("#pdf-search-status"),
  pdfSearchResults: $("#pdf-search-results"),
  pdfSearchClear: $("#pdf-search-clear"),
  pdfQaForm: $("#pdf-qa-form"),
  pdfQaInput: $("#pdf-qa-input"),
  pdfQaStatus: $("#pdf-qa-status"),
  pdfQaResult: $("#pdf-qa-result"),
};

/* Views routed by location.hash; every routable zone is hidden before the
   active one is shown (U1 keeps the single-zone-at-a-time contract). */
export const ZONES = [
  el.libraryZone, el.tagsZone, el.pdfSearchZone, el.inboxZone, el.settingsZone,
  el.timelineZone, el.graphZone, el.dashboardZone, el.uploadZone,
  el.workingZone, el.workZone, el.vaultExportZone, el.pdfZone,
];

export function hideAll() {
  ZONES.forEach((node) => { if (node) node.classList.add("hidden"); });
}

export function setBusy(busy) {
  state.busy = busy;
  [el.btnReparse, el.btnCopy, el.btnDownload, el.btnDelete, el.navUpload]
    .forEach((node) => { if (node) node.disabled = busy; });
}
